# Generated by Django 4.2.30 on 2026-09-08 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design', models.CharField(choices=[('1', 'Design 1 (pairwise)'), ('2', 'Design 2 (ranking)')], max_length=1)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('validation_accuracy', models.FloatField(blank=True, null=True)),
                ('fitted_weights', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField()),
                ('phase', models.CharField(choices=[('elicit', 'Elicitation'), ('validate', 'Validation')], max_length=10)),
                ('movies_shown', models.JSONField()),
                ('winner_index', models.IntegerField(blank=True, null=True)),
                ('ranking_order', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='project4.studysession')),
            ],
            options={
                'ordering': ['session', 'phase', 'round_number'],
            },
        ),
    ]
